
insert into table corresp_departamento ('id_departamento','nombre_departamento','nombre_division') values

('bnphu-adm', 'Administracion', ''),
('bnphu-adm-dc', 'Administracion', 'División de Contabilidad'),
('bnphu-adm-dcc', 'Administracion', 'División de Compras  y Contrataciones'),
('bnphu-adm-das', 'Administracion', 'División de Almacén y Suministro'),
('bnphu-adm-sac', 'Administracion', 'Sección de Archivo y Correspondencia '),
('bnphu-adm-dsg', 'Administracion', 'División de Servicios Generales'),
('bnphu-cac', 'Catalogación y Administración de Colecciones', ''),
('bnphu-cac-dac', 'Catalogación y Administración de Colecciones', 'División de Administración de Colecciones'),
('bnphu-cac-dh', 'Catalogación y Administración de Colecciones', 'División de Hemeroteca'),
('bnphu-com', 'Comunicacion', ''),
('bnphu-com-dp', 'Comunicacion', 'División de Publicaciones '),
('bnphu-com-dpe', 'Comunicacion', 'División de Protocolo y Eventos'),
('bnphu-dc', 'Desarrollo de colecciones', ''),
('bnphu-dc-ddl', 'Desarrollo de Colecciones', 'División de Depósito Legal'),
('bnphu-dn', 'Direccion Nacional', ''),
('bnphu-dn-dpd', 'Direccion Nacional', 'Departamento de Planificación y Desarrollo'),
('bnphu-dn-olai', 'Direccion Nacional', 'Oficina de Libre Acceso a la Información'),
('bnphu-dn-ds', 'Direccion Nacional', 'Departamento de Seguridad'),
('bnphu-dn-rrhh', 'Direccion Nacional', 'Departamento de  Recursos Humanos'),
('bnphu-dn-tic', 'Direccion Nacional', 'Departamento de Tecnología de la Información y Comunicación'),
('bnphu-dt', 'Direccion Tecnica', ''),
('bnphu-dt-dcb', 'Direccion Tecnica', 'Departamento de Capacitación en Bibliotecología'),
('bnphu-dt-isbn-issn', 'Direccion Tecnica', 'División ISBN /ISSN'),
('bnphu-dt-dgc', 'Direccion Tecnica', 'Departamento de Gestión Cultural'),
('bnphu-pcd', 'Preservación y Conservación de Documentos', ''),
('bnphu-pcd-de', 'Preservación y Conservación de Documentos', 'Division de Encuadernación'),
('bnphu-pcd-dlpd', 'Preservación y Conservación de Documentos', 'División de Laboratorio para la Preservación Documental'),
('bnphu-pd', 'Produccion Digital', ''),
('bnphu-pd-ssb', 'Produccion Digital', 'Sección de Soporte Bibliotecologico'),
('bnphu-pd-dbd', 'Produccion Digital', 'División de Biblioteca Digital'),
('bnphu-pd-ddd', 'Produccion Digital', 'División de Digitalización Documental'),
('bnphu-rnbp', 'Red Nacional de Bibliotecas Públicas', ''),
('bnphu-rnbp-bpjsl', 'Red Nacional de Bibliotecas Públicas', 'Biblioteca Pública Juan Sanchez Lamouth'),
('bnphu-rnbp-bprmb', 'Red Nacional de Bibliotecas Públicas', 'Biblioteca Pública Rafael Maria Baralt'),
('bnphu-rnbp-bppjb', 'Red Nacional de Bibliotecas Públicas', 'Biblioteca Pública Profesor Juan Bosch'),
('bnphu-sp', 'Servicios Publicos', ''),
('bnphu-sp-dapd', 'Servicios Publicos', 'División de Atención a Personas con Discapacidad')
