INSERT INTO corresp_instituciones('nombre_institucion', 'acronimo_institucion') VALUES 
('Acuario Nacional',''),
('Administradora de Estancias Infantiles Salud Segura','AEISS'),
('Administradora de Subsidios Sociales','EDESS'),
('AMERIPOL',''),
('Archivo General de la Nación','AGN'),
('Aseguradora Agropecuaria Dominicana','AGRODOSA'),
('Autoridad Nacional de Asuntos Marítimos','ANAMAR'),
('Autoridad Portuaria Dominicana','PORTTUARIA'),
('Banco Agrícola de la República Dominicana','BAGRICOLA'),
('Banco Central de la República Dominicana','BANCENTRAL'),
('Banco de Reservas de la República Dominicana','BANRESERVAS'),
('Banco Nacional de las Exportaciones','BANDEX'),
('Biblioteca Nacional Pedro Henríquez Ureña','BNPHU'),
('Cámara de Cuentas de la República Dominicana','CCRD'),
('Centro de Atención Integral para la Discapacidad','CAID'),
('Centro de Capacitación en Planificación e Inversión Pública','CCPIP'),
('Centro de Capacitación en Política y Gestión Fiscal','CAPGEFI'),
('Centro de Desarrollo y Competitividad Industrial','PROINDUSTRIA'),
('Centro de Exportación e Inversión de la República Dominicana','CEIRD'),
('Centro de Operaciones de Emergencia','COE'),
('Comedores Económicos del Estado Dominicano','CEED'),
('Comisión de Reforma de la Empresa Pública',''),
('Comisión Nacional de Defensa de la Competencia','PROCOMPETENCIA'),
('Comisión Nacional de Energía','CNE'),
('Comisión Permanente de Efemérides Patrias','CPEP'),
('Comisión Permanente de la Feria del Libro','CPFL'),
('Comisión Permanente de Titulación de Terrenos del Estado','TITUTLACION'),
('Comisión Reguladora de Prácticas Desleales en el Comercio y Medidas de Salvaguardas','CDC'),
('Consejo Asesor en Materia de Lucha Anticorrupción de la Presidencia de la República','LATINNO'),
('Consejo de Asesores Económicos del Poder Ejecutivo','CAPE'),
('Consejo del Poder Judicial',''),
('Consejo Dominicano para la Calidad','INDOCAL'),
('Consejo Intersectorial para la Política del Libro, la Lectura y las Bibliotecas','CONLIBRO'),
('Consejo Nacional de Competitividad','COMPETITIVIDAD'),
('Consejo Nacional de Discapacidad','CONADIS'),
('Consejo Nacional de Drogas','CND'),
('Consejo Nacional de Estancias Infantiles','CONDEI'),
('Consejo Nacional de Fronteras','CNF'),
('Consejo Nacional de Investigaciones Agropecuarias y Forestales','CONIAF'),
('Consejo Nacional de la Empresa Privada','CONEP'),
('Consejo Nacional de la Magistratura','CNM'),
('Consejo Nacional de la Persona Envejeciente','CONAPE'),
('Consejo Nacional de la Seguridad Social','CNSS'),
('Consejo Nacional de la Vivienda Económica','CNVE'),
('Consejo Nacional de Medio Ambiente y Recursos Naturales','AMBIENTE'),
('Consejo Nacional de Población y Familia','CONAPOFA'),
('Consejo Nacional para el Cambio Climático y Mecanismo de Desarrollo Limpio','CAMBIOCLIMATICO'),
('Consejo Nacional para el VIH y el SIDA','CONAVIHSIDA'),
('Consejo Nacional para la Niñez y la Adolescencia','CONANI'),
('Consultoría de Cooperación, Educación, Ciencia y Tenología','CONSULTORIA'),
('Consultoría Jurídica del Poder Ejecutivo','CJPE'),
('Contraloría General de la República','CGR'),
('Corporación Dominicana de Empresas Eléctricas Estatales','CDEEE'),
('Corporación Estatal de Radio y Televisión','CERTV'),
('Cruz Roja Dominicana','CRUZROJA'),
('Defensor del Pueblo','DP'),
('Departamento Nacional de Investigaciones','DNI'),
('Despacho de la Primera Dama','DPD'),
('Dirección de Información y Defensa de los Afiliados','DIDA'),
('Dirección de Información, Análisis y Programación Estratégica','DIAPE'),
('Dirección General Administrativa Financiera','DGAF'),
('Dirección General de Aduanas','DGA'),
('Dirección General de Análisis y Política Fiscal','DGAPF'),
('Dirección General de Bellas Artes',''),
('Dirección General de Bienes Nacionales','BN'),
('Dirección General de Catastro Nacional','DGCN'),
('Dirección General de Cine','DGCINE'),
('Dirección General de Compras y Contrataciones Públicas','DGCP'),
('Dirección General de Comunicación','DICOM'),
('Dirección General de Comunidad Digna','COMUNIDADDIGNA'),
('Dirección General de Contabilidad Gubernamental','DIGECOG'),
('Dirección General de Cooperación Bilateral','DIGECOOB'),
('Dirección General de Cooperación Multilateral','DIGECOOM'),
('Dirección General de Crédito Público','CD'),
('Dirección General de Desarrollo de la Comunidad','DGDC'),
('Dirección General de Desarrollo Económico y Social','DGDES'),
('Dirección General de Desarrollo Fronterizo','DGDF'),
('Dirección General de Edificaciones','DGE'),
('Dirección General de Educación Inicial','DGEI'),
('Dirección General de Embellecimiento de Carreteras y Avenidas de Circunvalación del País','DGECAC'),
('Dirección General de Estudios, Diseño de Infraestructura y Presupuesto','DIGEDIP'),
('Dirección General de Ética e Integridad Gubernamental','DIGEIG'),
('Dirección General de Ganadería','DIGEGA'),
('Dirección General de Higiene y Seguridad Industrial','DGHSI'),
('Dirección General de Historia Militar','DGHM'),
('Dirección General de Impuestos Internos','DGII'),
('Dirección General de Inversión Pública','DGIP'),
('Dirección General de Jubilaciones y Pensiones a Cargo del Estado','DGJP'),
('Dirección General de la Policía Nacional','DGPN'),
('Dirección General de las Reservas de las Fuerzas Armadas','DGRFA'),
('Dirección General de Medicamentos, Alimentos y Productos Sanitarios','DGMAPS'),
('Dirección General de Migración','MIGRACION'),
('Dirección General de Minería','DGM'),
('Dirección General de Ordenamiento y Desarrollo Territorial','DGODT'),
('Dirección General de Pasaportes','DGP'),
('Dirección General de Planificación y Desarrollo','DGPD'),
('Dirección General de Política y Legislación Tributaria','DGPLT'),
('Dirección General de Presupuesto','DIGEPRES'),
('Dirección General de Prisiones','DGP'),
('Dirección General de Programas Especiales de la Presidencia','DIGEPEP'),
('Dirección General de Riesgos Agropecuarios','DIGERA'),
('Dirección General de Seguridad de Tránsito y Transporte Terrestre','DIGESETT'),
('Dirección Nacional de Control de Drogas','DNCD'),
('Dirección Nacional de Registro de Títulos','DNRT'),
('Dirección Policial de Protección de Dignatarios','DPPD'),
('Empresa de Generación Hidroeléctrica Dominicana','EGEHID'),
('Empresa de Transmisión Eléctrica Dominicana','ETED'),
('Empresa Distribuidora de Electricidad del Este, S. A.','EDEESTE'),
('Empresa Distribuidora de Electricidad del Norte, S. A.','EDENORTE'),
('Empresa Distribuidora de Electricidad del Sur, S. A.','EDESUR'),
('Fondo de Pensiones de Trabajadores de la Construcción','FOPETCONS'),
('Fondo de Promocion a las Iniciativas Comunitarias','PROCOMUNIDAD'),
('Fondo Especial para el Desarrollo Agropecuario','FEDA'),
('Fondo Nacional para el Medio Ambiente y Recursos Naturales','FONDOMARENA'),
('Fondo Patrimonial de las Empresas Reformadas','FONPER'),
('Fundación Global Democracia y Desarrollo','FUNGLODE'),
('Fundacion Institucionalidad y Justicia','FINJUS'),
('Gabinete de Coordinación de la Política Económica','GCPE'),
('Gabinete de Coordinación de Política Institucional','GCPI'),
('Gabinete de Coordinación de Política Medioambiental y Desarrollo Físico','GCPS'),
('Gabinete de Coordinación de Políticas Sociales','GCPS'),
('Gobernación de las Oficinas Gubernamentales Prof. Juan Bosch','GOGPJB'),
('Gobernación Edificio de Oficinas Gubernamentales Juan Pablo Duarte','GOGOJPD'),
('Instituto Dominicano de Aviación Civil','IDAC'),
('Instituto Dominicano de Evaluación e Investigación de la Calidad Educativa','IDEICE'),
('Instituto Dominicano de Investigaciones Agropecuarias y Forestales','IDIAF'),
('Instituto Dominicano de las Telecomunicaciones','INDOTEL'),
('Instituto Dominicano de Seguros Sociales','IDSS'),
('Instituto Dominicano para la Calidad','INDOCAL'),
('Instituto Duartiano','ID'),
('Instituto Especializado de Estudios Superiores','IPES'),
('Instituto Nacional de Administración Pública','INAP'),
('Instituto Nacional de Aguas Potables y Alcantarillados','INAPA'),
('Instituto Nacional de Formación Técnico Profesional','INFOTEP'),
('Instituto Nacional de Formación Técnico Profesional Oficina Nacional','INFOTEP'),
('Instituto Nacional de Formación Técnico Profesional Regional Este','INFOTEP'),
('Instituto Nacional de Formación Técnico Profesional Regional Gerencia Central','INFOTEP'),
('Instituto Nacional de Formación Técnico Profesional Regional Norte','INFOTEP'),
('Instituto Nacional de Formación Técnico Profesional Regional Sur','INFOTEP'),
('Instituto Nacional de Formación y Capacitación del Magisterio','INFOCAM'),
('Instituto Nacional de la Vivienda','INVI'),
('Instituto Nacional de Migración','INM'),
('Instituto Nacional de Patología Forense','INACIF'),
('Instituto Nacional de Protección de los Derechos del Consumidor','PROCONSUMIDOR'),
('Instituto Nacional de Recursos Hidráulicos','INDRHI'),
('Instituto Nacional de Tránsito y Transporte Terrestre','INTRANT'),
('Instituto Postal Dominicano','INPOSDOM'),
('Jefatura de la Policía Nacional','JPN'),
('Junta Central Electoral','JCE'),
('Junta de Aviación Civil','JAC'),
('Junta Monetaria',''),
('Liga Municipal Dominicana','LMD'),
('Lotería Nacional','LN'),
('Mercados Dominicanos de Abasto Agropecuario','MERCADOM'),
('Ministerio Administrativo de la Presidencia','MAPRE'),
('Ministerio de Administración Pública','MAP'),
('Ministerio de Agricultura','AGRICULTURA'),
('Ministerio de Cultura','CULTURA'),
('Ministerio de Defensa','MD'),
('Ministerio de Deportes y Recreación','MIREDEC'),
('Ministerio de Economía, Planificación y Desarrollo','MEPyD'),
('Ministerio de Educación','ME'),
('Ministerio de Educación Superior, Ciencia y Tecnología','MESCyT'),
('Ministerio de Energía y Minas','MEM'),
('Ministerio de Hacienda','HACIENDA'),
('Ministerio de Industria, Comercio y Mipymes','MICM'),
('Ministerio de Interior y Policia','MIP'),
('Ministerio de la Juventud','JUVENTUD'),
('Ministerio de la Mujer','MUJER'),
('Ministerio de la Presidencia','MINPRE'),
('Ministerio de Medio Ambiente y Recursos Naturales','AMBIENTE'),
('Ministerio de Obras Públicas y Comunicaciones','MOPC'),
('Ministerio de Relaciones Exteriores','MIREX'),
('Ministerio de Salud Pública y Asistencia Social','MSP'),
('Ministerio de Trabajo','MT'),
('Ministerio de Turismo','MITUR'),
('Ministerio Público','MP'),
('Museo del Hombre Dominicano','MHD'),
('Museo Nacional de Historia Natural "Prof. Eugenio de Jesús Marcano"','MNHN'),
('Museo Policial Dominicano','MPD'),
('Oficina de Coordinación Presidencial','OCP'),
('Oficina de Custodia y Administración de Bienes Incautados y Decomisados','OCABID'),
('Oficina de Ingenieros Supervisores de Obras del Estado','OISOE'),
('Oficina Metropolitana de Servicios de Autobuses','OMSA'),
('Oficina Nacional de Defensa Pública','ONDP'),
('Oficina Nacional de Derecho de Autor','ONDA'),
('Oficina Nacional de Estadística','ONE'),
('Oficina Nacional de Evaluación Sísmica y Vulnerabilidad de Infraestructura y Edificaciones','ONESVIE'),
('Oficina Nacional de la Propiedad Industrial ','ONAPI'),
('Oficina Nacional de Meteorología','ONAMET'),
('Oficina para el Reordenamiento del Transporte','OPRET'),
('Oficina Presidencial de Tecnologías de la Información y Comunicación','OPTIC'),
('Oficina Técnica de Transporte Terrestre','OTTT'),
('Organismo Dominicano de Acreditación','ODAC'),
('Plan de Asistencia Social de la Presidencia','PASP'),
('Policía Nacional','PN'),
('Presidencia de la República','PR'),
('Procuraduría Fiscal del Distrito Judicial del Distrito Nacional','PFDJDN'),
('Procuraduría General de la República Dominicana','PGRD'),
('Refinería Dominicana de Petróleo','REFIDOM'),
('Seguro Nacional de Salud','SNS'),
('Senado de la República Dominicana','SENADO'),
('Sistema de Monitoreo de la Administracion Pública','SISMAP'),
('Sistema Nacional de Atención a Emergencias y Seguridad 9-1-1','SNAES'),
('Sistema Unico de Beneficiarios','SIUBEN'),
('Superintendencia de Bancos','SIB'),
('Superintendencia de Electricidad','SIE'),
('Superintendencia de Pensiones','SIP'),
('Superintendencia de Salud y Riesgos Laborales','SISALRIL'),
('Superintendencia de Seguros','SUPERSEGUROS'),
('Superintendencia de Valores','SIV'),
('Superintendencia de Vigilancia y Seguridad Privada','SVSP'),
('Suprema Corte de Justicia','SCJ'),
('Teatro Nacional',''),
('Tesorería de la Seguridad Social','TSS'),
('Tesorería Nacional','TESORERIA'),
('Tribunal Constitucional','TC'),
('Tribunal Superior Electoral','TSE'),
('Unidad de Análisis Financiero','UAF'),
('Unidad de Salud Mental Prof. Ramón Rey Ardid','UNIHSAM'),
('Universidad Autónoma de Santo Domingo','UASD')