

insert into corresp_rol (nombre_rol, status_rol) values 
('Abogado (a)', 'A'),
('Administrador de Aleph', 'A'),
('Administrador de Red', 'A'),
('Administrador de Sistemas', 'A'),
('Analista de Activo Fijo', 'A'),
('Analista de Compensación y Beneficios', 'A'),
('Analista de Contabilidad', 'A'),
('Analista de Formulación, Monitoreo y Evaluación de planes y proyectos', 'A'),
('Analista de Nómina', 'A'),
('Analista de registroControl', 'A'),
('Analista Institucional y Calidad en la Gestión', 'A'),
('Archivista', 'A'),
('Asesor', 'A'),
('Asistente ', 'A'),
('Asistente Administrativa', 'A'),
('Auxilair de Protocolo', 'A'),
('Auxiliar Bibliotecario ', 'A'),
('Auxiliar Bibliotecario I', 'A'),
('Auxiliar Bibliotecario II', 'A'),
('Auxiliar de Administrativo I', 'A'),
('Auxiliar de Almacén', 'A'),
('Auxiliar de Limpieza de Libros', 'A'),
('Auxiliar de Mayordomia', 'A'),
('Ayudante de Mantenimiento', 'A'),
('Bibliotecologo (a)', 'A'),
('Camarero', 'A'),
('Chofer I', 'A'),
('Conserje ', 'A'),
('Consultor Jurídico', 'A'),
('Coordinador (a)', 'A'),
('Coordinador (a) Docente', 'A'),
('Coordinador (a) Medios Digitales', 'A'),
('Coordinador Bibliotecario', 'A'),
('Corrector (a) de Estilo', 'A'),
('Corrector de Estilo', 'A'),
('Digitador', 'A'),
('Director Nacional ', 'A'),
('Directora Técnica Bibliotecologica', 'A'),
('Diseñador Gráfico', 'A'),
('Electricista', 'A'),
('Encargado de División', 'A'),
('Encargado de Departamento', 'A'),
('Encargado de Sección', 'A'),
('Encargado Financiero ', 'A'),
('Encuadernador', 'A'),
('Facilitador(a)', 'A'),
('Fotógrafo', 'A'),
('Mecánico', 'A'),
('Mensajero ', 'A'),
('Mensajero Interno', 'A'),
('Notario Público', 'A'),
('Operador de Controlde Calidad', 'A'),
('Operador de Scanner', 'A'),
('Periodista', 'A'),
('Promotor (a)', 'A'),
('Recepcionista', 'A'),
('Secretaria ', 'A'),
('Secretaria Ejecutiva', 'A'),
('Soporte Tecnico', 'A'),
('Supervisor de Mantenimiento', 'A'),
('Supervisora ', 'A'),
('Tecnico Bibliotecario', 'A'),
('Técnico de Audio de Libro', 'A'),
('Tecnico de Recursos Humanos', 'A'),
('Técnico de Sonido', 'A'),
('Técnico en Compras', 'A'),
('Técnico en Restauración y  Encuadernación', 'A'),
('Vigilante', 'A'),
('WebMaster', 'A')


